<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE student [ 
<!ELEMENT student (name,address,std,br,marks)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT address (#PCDATA)> 
<!ELEMENTstd (#PCDATA)> 
<!ELEMENT br EMPTY> 
<!ELEMENT marks (#PCDATA)> 
]> 
<student> 
 <name>Anand</name> 
 <address>Pune</address> 
 <std>Second</std> 
 <br /> 
 <marks>70 percent</marks> 
</student>